/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedAdminStudentsRouteImport } from './routes/_protected/admin/students'
import { Route as ProtectedAdminSettingsRouteImport } from './routes/_protected/admin/settings'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminStudentsRoute = ProtectedAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin/students': typeof ProtectedAdminStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin/students': typeof ProtectedAdminStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/admin/settings': typeof ProtectedAdminSettingsRoute
  '/_protected/admin/students': typeof ProtectedAdminStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/unauthorized'
    | '/_protected/admin'
    | '/(auth)/login'
    | '/_protected/admin/dashboard'
    | '/_protected/admin/settings'
    | '/_protected/admin/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/students': {
      id: '/_protected/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof ProtectedAdminStudentsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/settings': {
      id: '/_protected/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedAdminStudentsRoute: typeof ProtectedAdminStudentsRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedAdminStudentsRoute: ProtectedAdminStudentsRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
